#!/bin/bash

SBT_BOOT_DIR=$HOME/.sbt/boot/

if [ ! -d "$SBT_BOOT_DIR" ]; then
  mkdir -p $SBT_BOOT_DIR
fi

cat /dev/null | java -Xmx1536M -XX:MaxPermSize=384M -XX:+UseCompressedOops -XX:+CMSClassUnloadingEnabled \
    -Dsbt.log.noformat=true \
    -Dbuild.configuation.name="$TEAMCITY_BUILDCONF_NAME" \
    -Dbuild.number="$BUILD_NUMBER" \
    -Dbuild.vcs.number="$BUILD_VCS_NUMBER" \
    -Dsbt.boot.directory=$SBT_BOOT_DIR \
    -Dfile.encoding=UTF8 \
    -jar sbt-launch.jar "$@"
